TheTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace TheTreats.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.Treats = new HashSet<FlavorTreat>();
    }

    public int FlavorId { get; set; }
    public string FlavorName { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<FlavorTreat> Treats { get; set; }
  }
}

TheTreats/Controllers/FlavorsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheTreats.Models;

namespace TheTreats.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly TheTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, TheTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [Authorize]
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userFlavors = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userFlavors);
    }

    [Authorize]
    public ActionResult Create()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var thisUsersTreats = _db.Treats.Where(entry => entry.User.Id == userId);
      ViewBag.TreatId = new SelectList(thisUsersTreats, "TreatId", "Name");
      return View(); 
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value; 
      var currentUser = await _userManager.FindByIdAsync(userId); 
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors 
        .Include(flavor => flavor.Treats) 
        .ThenInclude(join => join.Treat) 
        .FirstOrDefault(flavor => flavor.FlavorId == id); 
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId}); 
      }
      _db.Entry(flavor).State = EntityState.Modified; 
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      var existingConnection = _db.FlavorTreat.FirstOrDefault(join => join.FlavorId == flavor.FlavorId && join.TreatId == TreatId);

      if (existingConnection != null)
      {
        return RedirectToAction("Details", new {id = flavor.FlavorId});
      }
      if (TreatId != 0)
      {
      _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TheTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Flavor

<h1>Add a new flavor</h1>
<hr/>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FlavorName)
  @Html.TextBoxFor(model => model.FlavorName)
  <br>
  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")
  <br>
  <input type="submit" value="Add new flavor" class="btn btn=default" />
}
<br>
<p>@Html.ActionLink("Back to flavor", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Flavor

<h2>Delete Flavor:</h2>
<hr/>
@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
    
    <input type="submit" value="Delete" />
}
<br>
<p>@Html.ActionLink("Back to Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p> 

TheTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Flavor

<h1>Flavor Details</h1>
<hr/>
<h3>@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)</h3>
<br>
@if(@Model.Treats.Count == 0)
{
  <p>This flavor has not yet been assigned to a treat</p>
}
else
{
  <h4>This flavors associated treat:</h4>
  <ul>
  @foreach(var join in Model.Treats)
  {
    <li><p>@join.Treat.Name</p></li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<br>
<p>@Html.ActionLink("Edit flavor", "Edit", new { id = Model.FlavorId})</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Back to flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Flavor

<h1>Edit Flavor</h1>
<hr/>
@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)
<br>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  @Html.LabelFor(model => model.FlavorName)
  @Html.EditorFor(model => model.FlavorName)
  <br>
  @Html.Label("Select Treat")
  @Html.DropDownList("TreatId")
  <br>
  <input type="submit" value="Add new Flavor" class="btn btn=default" />
}
<br>
<p>@Html.ActionLink("Back to Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using TheTreats.Models;
@using TheTreats.ViewModels;
@using System.Security.Claims
@model IEnumerable<TheTreats.Models.Flavor>

<h1>@User.Identity.Name's Flavors</h1>
<hr/>
@if(Model.Any())
{
  <ul>
  @foreach(Flavor flavor in Model)
  {
    <li><p>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId})</p></li>
  }
  </ul>
}
else
{
  <p>No Flavors have been added yet!</p>
}
<br>
<p>@Html.ActionLink("Add new flavor", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>