TheTreats/Models/Treat.cs
using System.Collections.Generic;

namespace TheTreats.Models
{
  public class Treat
  {
    public Treat()
    {
      this.Flavors = new HashSet<FlavorTreat>();
      
    }

    public int TreatId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<FlavorTreat> Flavors { get; set; } 
  }
}

TheTreats/Controllers/TreatsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheTreats.Models;

namespace TheTreats.Cotrollers
{
  public class TreatsController : Controller
  {
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly TheTreatsContext _db;

    public TreatsController(UserManager<ApplicationUser> userManager, TheTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [Authorize]
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userTreats = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userTreats); 
    }

    [Authorize]
    public ActionResult Create()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var thisUsersFlavors = _db.Flavors.Where(entry => entry.User.Id == userId);
      ViewBag.FlavorId = new SelectList(thisUsersFlavors, "FlavorId", "FlavorName");
      return View(); 
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value; 
      var currentUser = await _userManager.FindByIdAsync(userId); 
      treat.User = currentUser;
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats 
        .Include(treat => treat.Flavors) 
        .ThenInclude(join => join.Flavor) 
        .Include(treat => treat.User)
        .FirstOrDefault(treat => treat.TreatId == id); 
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ViewBag.IsCurrentUser = userId != null ? userId == thisTreat.User.Id : false;    
      return View(thisTreat);
    }

    [Authorize]
    public async Task<ActionResult> Edit(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName"); 
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId }); 
      }
      _db.Entry(treat).State = EntityState.Modified; 
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> Delete(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      
      Treat thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> AddFlavor(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      var existingConnection = _db.FlavorTreat.FirstOrDefault(join => join.TreatId == treat.TreatId && join.FlavorId == FlavorId);
      if (existingConnection != null)
      {
        return RedirectToAction("Details", new {id = treat.TreatId});
      }
      if (FlavorId != 0)
      {
      _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TheTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Treat

<h1>Add a new treat</h1>
<hr/>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <br>
  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")
  <br>
  <input type="submit" value="Add new treat" class="btn btn=default" />
}
<br>
<p>@Html.ActionLink("Back to treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Treat

<h2>Delete Treat:</h2>
<hr/>
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    
    <input type="submit" value="Delete" />
}
<br>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using System.Security.Claims
@model TheTreats.Models.Treat

<h1>Treat Details</h1>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<br>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<br>
@if(@Model.Flavors.Count == 0)
{
  <p>You have not chosen a flavor for your Treat</p>
}
else
{
  <h4>This treats flavors:</h4>
  <ul>
  @foreach(var join in @Model.Flavors)
  {
    <li><p>@join.Flavor.FlavorName</p></li>
    @if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
    {
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }  
  }
  </ul>
}
<br>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

@if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
{
  <p>@Html.ActionLink("Edit treat", "Edit", new { id = Model.TreatId})</p>
  <p>@Html.ActionLink("Delete treat", "Delete", new { id = Model.TreatId })</p>
}

TheTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TheTreats.Models.Treat

<h1>Edit Treat</h1>
<hr/>
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
<br>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  <br>
  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")
  <br>
  <input type="submit" value="Add new Treat" class="btn btn=default" />
}
<br>
<p>@Html.ActionLink("Back to Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using TheTreats.Models;
@using System.Security.Claims
@model IEnumerable<TheTreats.Models.Treat>

<h1>@User.Identity.Name's Treats</h1>
<hr/>
@if(Model.Any())
{
  <ul>
  @foreach(Treat treat in Model)
  {
    <li><p>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId})</p></li>
  }
  </ul>
}
else
{
  <p>No Treats have been added yet!</p>
}
<br>
@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add new Treat", "Create")</p>
}
<p>@Html.ActionLink("Home", "Index", "Home")</p>